apiVersion: v1
kind: Service
metadata:
  name: ticket-booking-nodeport
  namespace: default
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
  selector:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/component: controller
