apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  namespace: default
data:
  my.cnf: |
    [mysqld]
    default-authentication-plugin=mysql_native_password
    bind-address = 0.0.0.0
    innodb_buffer_pool_size = 512M
    max_connections = 200
    slow_query_log = 1
    long_query_time = 2
    general_log = 1
    general_log_file = /var/lib/mysql/general.log
