apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-service
  namespace: default
  labels:
    app: event-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: event-service
  template:
    metadata:
      labels:
        app: event-service
    spec:
      containers:
      - name: event-service
        image: event-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3002
        env:
        - name: DB_HOST
          value: mysql-service
        - name: DB_USER
          value: ticketuser
        - name: DB_PASSWORD
          value: ticketpassword
        - name: DB_NAME
          value: ticket_booking
        - name: REDIS_HOST
          value: redis-service
        resources:
          limits:
            memory: "256Mi"
            cpu: "250m"
          requests:
            memory: "128Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3002
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 3002
          initialDelaySeconds: 10
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: event-service
  namespace: default
spec:
  selector:
    app: event-service
  ports:
  - port: 80
    targetPort: 3002
  type: ClusterIP
